rain <- read.table(file = "E:/Study in Columbia/Research/data/train_vector_4C50.dat",header=FALSE)
test <- read.table(file = "E:/Study in Columbia/Research/data/test_vector_4C50.dat",header=FALSE)
library(C50)
treeModel <- C5.0(train[,-1],factor(train[,1]))
prediction = predict(treeModel, test[,-1])
label = factor(test[,1])
p <- as.numeric(as.character(prediction))
l <- as.numeric(as.character(label))
prob = predict(treeModel, test[,-1],type = "prob")
true = t(p) %*% l + t(p-1) %*% (l-1)
accuracy = true/nrow(test)
